### ISSUE TITLE
Dash??

### ISSUE THREAD

**Issue by Cromiad** [KEN-2000l/EducationPerfected#15]
Not really a problem, but the read me says it works with dash, I've tried both normal scripts and script+, doesn't work. Is there something that I am doing wrong, or have you guys not developed that yet? 

Also, script+ doesn't seem to work at all for me

**Comment by garv-shah** [comment]
if you're having issues with it being too fast, you can always use this version of the script (https://github.com/KEN-2000l/EducationPerfected/issues/16), but as far as i'm aware, dash seems to work fine. i'll close the issue due to inactivity, but feel free to open it whenever with the screenshots, etc
(:
