### ISSUE TITLE
Release issues

### ISSUE THREAD

**Issue by Susmaster64** [KEN-2000l/EducationPerfected#22]
a and r button not keyed on latest release (2.0.0). Names for scripts are the wrong way around (I think)

**Comment by garv-shah** [comment]
version 2.0.0 is actually script+.js, and most likely shouldn't be used
in fact, i'll remove that release for now due to the fact that it's so unstable
so i'd consider this issue a part of https://github.com/KEN-2000l/EducationPerfected/issues/12 and i have no clue how script+ works, so as mentioned in that issue, you'd have to ask ken, or we'd remake it from scratch when we get time
