### ISSUE TITLE
no need for auto browser download

### ISSUE THREAD

**Issue by KEN-2000l** [KEN-2000l/EducationPerfected#35]
@garv-shah i was looking at the changes when you fixed sso login (3256bd96a3371fd37d87213a2d41d2991b7615eb)

I see that you have added some lines that downloads a browser
is it really necessary? because `npm i puppeteer` will install a bundled chromium browser, which should always work anyway

**Comment by garv-shah** [comment]
i think it's a MacOS thing with chromium, cause it worked fine for me on windows but on MacOS it told me that it could only run on chromium revision something, so adding in the auto-download line fixed it on MacOS
I think it should be fine either way, since it doesn't seem to install another browser if the bundled browser already works :D

**Comment by KEN-2000l** [comment]
i see, all good then :)
